%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Andrew\Lai_SMULab\Projects\BicepsSensorArray\Reports\ReportSummary_V3.xlsm
%    Worksheet: Summary Heatmap
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/06/16 16:24:31

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Andrew\Lai_SMULab\Projects\BicepsSensorArray\Reports\ReportSummary_V3.xlsm','Summary Heatmap','A8:AS18');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
F_Test = table;

%% Allocate imported array to column variable names
F_Test.VarName1 = cellstr(stringVectors(:,1));
F_Test.Report = data(:,1);
F_Test.Report_MVC_Stroke_5_4_2017 = data(:,2);
F_Test.Report_MVC_Stroke_5_24_2017 = data(:,3);
F_Test.Report_MVC_Stroke_5_24_1 = data(:,4);
F_Test.Report_MVC_Stroke_5_24_2 = data(:,5);
F_Test.Report_MVC_Stroke_5_24_3 = data(:,6);
F_Test.Report_MVC_Stroke_5_24_4 = data(:,7);
F_Test.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_2017 = data(:,8);
F_Test.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_1 = data(:,9);
F_Test.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_2017 = data(:,10);
F_Test.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_1 = data(:,11);
F_Test.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2017 = data(:,12);
F_Test.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_1 = data(:,13);
F_Test.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2 = data(:,14);
F_Test.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_2017 = data(:,15);
F_Test.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_1 = data(:,16);
F_Test.Report_SEMG_SensorArray_SNR_Stroke_5_22_2017 = data(:,17);
F_Test.Report_SEMG_SensorArray_SNR_Stroke_5_22_1 = data(:,18);
F_Test.Report_SEMG_SensorArray_SNR_Stroke_5_22_2 = data(:,19);
F_Test.Report_SEMG_SensorArray_SNR_Stroke_5_22_3 = data(:,20);
F_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2017 = data(:,21);
F_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2017 = data(:,22);
F_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2017 = data(:,23);
F_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2017 = data(:,24);
F_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_1 = data(:,25);
F_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_1 = data(:,26);
F_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_1 = data(:,27);
F_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_1 = data(:,28);
F_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2 = data(:,29);
F_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2 = data(:,30);
F_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2 = data(:,31);
F_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2 = data(:,32);
F_Test.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_2017 = data(:,33);
F_Test.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_1 = data(:,34);
F_Test.Report_MU_Amplitudes_Vs_RecruitmentForce_Stroke_Threshold_5_19_ = data(:,35);
F_Test.Report_MU_Amplitudes_Vs_MeanFiringRate_Stroke_5_15_2017 = data(:,36);
F_Test.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_2017 = data(:,37);
F_Test.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_1 = data(:,38);
F_Test.Report_MU_Duration_Vs_RecruitmentForce_Stroke_Threshold_5_19_20 = data(:,39);
F_Test.Report_MU_Duration_Vs_MeanFiringRate_Stroke_Threshold_5_19_2017 = data(:,40);
F_Test.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_2017 = data(:,41);
F_Test.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_1 = data(:,42);
F_Test.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_19_20 = data(:,43);
F_Test.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_15_20 = data(:,44);

%% Clear temporary variables
clearvars data raw stringVectors R;


%% Import the data
[~, ~, raw] = xlsread('C:\Users\Andrew\Lai_SMULab\Projects\BicepsSensorArray\Reports\ReportSummary_V3.xlsm','Summary Heatmap','A20:AS30');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
T_Test = table;

%% Allocate imported array to column variable names
T_Test.VarName1 = cellstr(stringVectors(:,1));
T_Test.Report = data(:,1);
T_Test.Report_MVC_Stroke_5_4_2017 = data(:,2);
T_Test.Report_MVC_Stroke_5_24_2017 = data(:,3);
T_Test.Report_MVC_Stroke_5_24_1 = data(:,4);
T_Test.Report_MVC_Stroke_5_24_2 = data(:,5);
T_Test.Report_MVC_Stroke_5_24_3 = data(:,6);
T_Test.Report_MVC_Stroke_5_24_4 = data(:,7);
T_Test.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_2017 = data(:,8);
T_Test.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_1 = data(:,9);
T_Test.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_2017 = data(:,10);
T_Test.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_1 = data(:,11);
T_Test.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2017 = data(:,12);
T_Test.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_1 = data(:,13);
T_Test.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2 = data(:,14);
T_Test.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_2017 = data(:,15);
T_Test.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_1 = data(:,16);
T_Test.Report_SEMG_SensorArray_SNR_Stroke_5_22_2017 = data(:,17);
T_Test.Report_SEMG_SensorArray_SNR_Stroke_5_22_1 = data(:,18);
T_Test.Report_SEMG_SensorArray_SNR_Stroke_5_22_2 = data(:,19);
T_Test.Report_SEMG_SensorArray_SNR_Stroke_5_22_3 = data(:,20);
T_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2017 = data(:,21);
T_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2017 = data(:,22);
T_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2017 = data(:,23);
T_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2017 = data(:,24);
T_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_1 = data(:,25);
T_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_1 = data(:,26);
T_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_1 = data(:,27);
T_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_1 = data(:,28);
T_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2 = data(:,29);
T_Test.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2 = data(:,30);
T_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2 = data(:,31);
T_Test.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2 = data(:,32);
T_Test.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_2017 = data(:,33);
T_Test.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_1 = data(:,34);
T_Test.Report_MU_Amplitudes_Vs_RecruitmentForce_Stroke_Threshold_5_19_ = data(:,35);
T_Test.Report_MU_Amplitudes_Vs_MeanFiringRate_Stroke_5_15_2017 = data(:,36);
T_Test.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_2017 = data(:,37);
T_Test.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_1 = data(:,38);
T_Test.Report_MU_Duration_Vs_RecruitmentForce_Stroke_Threshold_5_19_20 = data(:,39);
T_Test.Report_MU_Duration_Vs_MeanFiringRate_Stroke_Threshold_5_19_2017 = data(:,40);
T_Test.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_2017 = data(:,41);
T_Test.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_1 = data(:,42);
T_Test.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_19_20 = data(:,43);
T_Test.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_15_20 = data(:,44);

%% Clear temporary variables
clearvars data raw stringVectors R;

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Andrew\Lai_SMULab\Projects\BicepsSensorArray\Reports\ReportSummary_V3.xlsm','Summary Heatmap','A44:AS54');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
AFF = table;

%% Allocate imported array to column variable names
AFF.VarName1 = cellstr(stringVectors(:,1));
AFF.Report = data(:,1);
AFF.Report_MVC_Stroke_5_4_2017 = data(:,2);
AFF.Report_MVC_Stroke_5_24_2017 = data(:,3);
AFF.Report_MVC_Stroke_5_24_1 = data(:,4);
AFF.Report_MVC_Stroke_5_24_2 = data(:,5);
AFF.Report_MVC_Stroke_5_24_3 = data(:,6);
AFF.Report_MVC_Stroke_5_24_4 = data(:,7);
AFF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_2017 = data(:,8);
AFF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_1 = data(:,9);
AFF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_2017 = data(:,10);
AFF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_1 = data(:,11);
AFF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2017 = data(:,12);
AFF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_1 = data(:,13);
AFF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2 = data(:,14);
AFF.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_2017 = data(:,15);
AFF.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_1 = data(:,16);
AFF.Report_SEMG_SensorArray_SNR_Stroke_5_22_2017 = data(:,17);
AFF.Report_SEMG_SensorArray_SNR_Stroke_5_22_1 = data(:,18);
AFF.Report_SEMG_SensorArray_SNR_Stroke_5_22_2 = data(:,19);
AFF.Report_SEMG_SensorArray_SNR_Stroke_5_22_3 = data(:,20);
AFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2017 = data(:,21);
AFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2017 = data(:,22);
AFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2017 = data(:,23);
AFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2017 = data(:,24);
AFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_1 = data(:,25);
AFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_1 = data(:,26);
AFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_1 = data(:,27);
AFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_1 = data(:,28);
AFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2 = data(:,29);
AFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2 = data(:,30);
AFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2 = data(:,31);
AFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2 = data(:,32);
AFF.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_2017 = data(:,33);
AFF.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_1 = data(:,34);
AFF.Report_MU_Amplitudes_Vs_RecruitmentForce_Stroke_Threshold_5_19_ = data(:,35);
AFF.Report_MU_Amplitudes_Vs_MeanFiringRate_Stroke_5_15_2017 = data(:,36);
AFF.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_2017 = data(:,37);
AFF.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_1 = data(:,38);
AFF.Report_MU_Duration_Vs_RecruitmentForce_Stroke_Threshold_5_19_20 = data(:,39);
AFF.Report_MU_Duration_Vs_MeanFiringRate_Stroke_Threshold_5_19_2017 = data(:,40);
AFF.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_2017 = data(:,41);
AFF.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_1 = data(:,42);
AFF.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_19_20 = data(:,43);
AFF.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_15_20 = data(:,44);

%% Clear temporary variables
clearvars data raw stringVectors R;


%% Import the data
[~, ~, raw] = xlsread('C:\Users\Andrew\Lai_SMULab\Projects\BicepsSensorArray\Reports\ReportSummary_V3.xlsm','Summary Heatmap','A56:AS66');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
UNAFF = table;

%% Allocate imported array to column variable names
UNAFF.VarName1 = cellstr(stringVectors(:,1));
UNAFF.Report = data(:,1);
UNAFF.Report_MVC_Stroke_5_4_2017 = data(:,2);
UNAFF.Report_MVC_Stroke_5_24_2017 = data(:,3);
UNAFF.Report_MVC_Stroke_5_24_1 = data(:,4);
UNAFF.Report_MVC_Stroke_5_24_2 = data(:,5);
UNAFF.Report_MVC_Stroke_5_24_3 = data(:,6);
UNAFF.Report_MVC_Stroke_5_24_4 = data(:,7);
UNAFF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_2017 = data(:,8);
UNAFF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_1 = data(:,9);
UNAFF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_2017 = data(:,10);
UNAFF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_1 = data(:,11);
UNAFF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2017 = data(:,12);
UNAFF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_1 = data(:,13);
UNAFF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2 = data(:,14);
UNAFF.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_2017 = data(:,15);
UNAFF.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_1 = data(:,16);
UNAFF.Report_SEMG_SensorArray_SNR_Stroke_5_22_2017 = data(:,17);
UNAFF.Report_SEMG_SensorArray_SNR_Stroke_5_22_1 = data(:,18);
UNAFF.Report_SEMG_SensorArray_SNR_Stroke_5_22_2 = data(:,19);
UNAFF.Report_SEMG_SensorArray_SNR_Stroke_5_22_3 = data(:,20);
UNAFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2017 = data(:,21);
UNAFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2017 = data(:,22);
UNAFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2017 = data(:,23);
UNAFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2017 = data(:,24);
UNAFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_1 = data(:,25);
UNAFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_1 = data(:,26);
UNAFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_1 = data(:,27);
UNAFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_1 = data(:,28);
UNAFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2 = data(:,29);
UNAFF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2 = data(:,30);
UNAFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2 = data(:,31);
UNAFF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2 = data(:,32);
UNAFF.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_2017 = data(:,33);
UNAFF.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_1 = data(:,34);
UNAFF.Report_MU_Amplitudes_Vs_RecruitmentForce_Stroke_Threshold_5_19_ = data(:,35);
UNAFF.Report_MU_Amplitudes_Vs_MeanFiringRate_Stroke_5_15_2017 = data(:,36);
UNAFF.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_2017 = data(:,37);
UNAFF.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_1 = data(:,38);
UNAFF.Report_MU_Duration_Vs_RecruitmentForce_Stroke_Threshold_5_19_20 = data(:,39);
UNAFF.Report_MU_Duration_Vs_MeanFiringRate_Stroke_Threshold_5_19_2017 = data(:,40);
UNAFF.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_2017 = data(:,41);
UNAFF.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_1 = data(:,42);
UNAFF.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_19_20 = data(:,43);
UNAFF.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_15_20 = data(:,44);

%% Clear temporary variables
clearvars data raw stringVectors R;


[~, ~, raw] = xlsread('C:\Users\Andrew\Lai_SMULab\Projects\BicepsSensorArray\Reports\ReportSummary_V3.xlsm','Summary Heatmap','A92:AS102');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
AFF_VAF = table;

%% Allocate imported array to column variable names
AFF_VAF.VarName1 = cellstr(stringVectors(:,1));
AFF_VAF.Report = data(:,1);
AFF_VAF.Report_MVC_Stroke_5_4_2017 = data(:,2);
AFF_VAF.Report_MVC_Stroke_5_24_2017 = data(:,3);
AFF_VAF.Report_MVC_Stroke_5_24_1 = data(:,4);
AFF_VAF.Report_MVC_Stroke_5_24_2 = data(:,5);
AFF_VAF.Report_MVC_Stroke_5_24_3 = data(:,6);
AFF_VAF.Report_MVC_Stroke_5_24_4 = data(:,7);
AFF_VAF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_2017 = data(:,8);
AFF_VAF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_1 = data(:,9);
AFF_VAF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_2017 = data(:,10);
AFF_VAF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_1 = data(:,11);
AFF_VAF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2017 = data(:,12);
AFF_VAF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_1 = data(:,13);
AFF_VAF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2 = data(:,14);
AFF_VAF.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_2017 = data(:,15);
AFF_VAF.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_1 = data(:,16);
AFF_VAF.Report_SEMG_SensorArray_SNR_Stroke_5_22_2017 = data(:,17);
AFF_VAF.Report_SEMG_SensorArray_SNR_Stroke_5_22_1 = data(:,18);
AFF_VAF.Report_SEMG_SensorArray_SNR_Stroke_5_22_2 = data(:,19);
AFF_VAF.Report_SEMG_SensorArray_SNR_Stroke_5_22_3 = data(:,20);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2017 = data(:,21);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2017 = data(:,22);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2017 = data(:,23);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2017 = data(:,24);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_1 = data(:,25);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_1 = data(:,26);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_1 = data(:,27);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_1 = data(:,28);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2 = data(:,29);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2 = data(:,30);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2 = data(:,31);
AFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2 = data(:,32);
AFF_VAF.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_2017 = data(:,33);
AFF_VAF.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_1 = data(:,34);
AFF_VAF.Report_MU_Amplitudes_Vs_RecruitmentForce_Stroke_Threshold_5_19_ = data(:,35);
AFF_VAF.Report_MU_Amplitudes_Vs_MeanFiringRate_Stroke_5_15_2017 = data(:,36);
AFF_VAF.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_2017 = data(:,37);
AFF_VAF.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_1 = data(:,38);
AFF_VAF.Report_MU_Duration_Vs_RecruitmentForce_Stroke_Threshold_5_19_20 = data(:,39);
AFF_VAF.Report_MU_Duration_Vs_MeanFiringRate_Stroke_Threshold_5_19_2017 = data(:,40);
AFF_VAF.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_2017 = data(:,41);
AFF_VAF.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_1 = data(:,42);
AFF_VAF.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_19_20 = data(:,43);
AFF_VAF.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_15_20 = data(:,44);

%% Clear temporary variables
clearvars data raw stringVectors R;


%% Import the data
[~, ~, raw] = xlsread('C:\Users\Andrew\Lai_SMULab\Projects\BicepsSensorArray\Reports\ReportSummary_V3.xlsm','Summary Heatmap','A104:AS114');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
UNAFF_VAF = table;

%% Allocate imported array to column variable names
UNAFF_VAF.VarName1 = cellstr(stringVectors(:,1));
UNAFF_VAF.Report = data(:,1);
UNAFF_VAF.Report_MVC_Stroke_5_4_2017 = data(:,2);
UNAFF_VAF.Report_MVC_Stroke_5_24_2017 = data(:,3);
UNAFF_VAF.Report_MVC_Stroke_5_24_1 = data(:,4);
UNAFF_VAF.Report_MVC_Stroke_5_24_2 = data(:,5);
UNAFF_VAF.Report_MVC_Stroke_5_24_3 = data(:,6);
UNAFF_VAF.Report_MVC_Stroke_5_24_4 = data(:,7);
UNAFF_VAF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_2017 = data(:,8);
UNAFF_VAF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_1 = data(:,9);
UNAFF_VAF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_2017 = data(:,10);
UNAFF_VAF.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_1 = data(:,11);
UNAFF_VAF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2017 = data(:,12);
UNAFF_VAF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_1 = data(:,13);
UNAFF_VAF.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2 = data(:,14);
UNAFF_VAF.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_2017 = data(:,15);
UNAFF_VAF.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_1 = data(:,16);
UNAFF_VAF.Report_SEMG_SensorArray_SNR_Stroke_5_22_2017 = data(:,17);
UNAFF_VAF.Report_SEMG_SensorArray_SNR_Stroke_5_22_1 = data(:,18);
UNAFF_VAF.Report_SEMG_SensorArray_SNR_Stroke_5_22_2 = data(:,19);
UNAFF_VAF.Report_SEMG_SensorArray_SNR_Stroke_5_22_3 = data(:,20);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2017 = data(:,21);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2017 = data(:,22);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2017 = data(:,23);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2017 = data(:,24);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_1 = data(:,25);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_1 = data(:,26);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_1 = data(:,27);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_1 = data(:,28);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2 = data(:,29);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2 = data(:,30);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2 = data(:,31);
UNAFF_VAF.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2 = data(:,32);
UNAFF_VAF.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_2017 = data(:,33);
UNAFF_VAF.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_1 = data(:,34);
UNAFF_VAF.Report_MU_Amplitudes_Vs_RecruitmentForce_Stroke_Threshold_5_19_ = data(:,35);
UNAFF_VAF.Report_MU_Amplitudes_Vs_MeanFiringRate_Stroke_5_15_2017 = data(:,36);
UNAFF_VAF.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_2017 = data(:,37);
UNAFF_VAF.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_1 = data(:,38);
UNAFF_VAF.Report_MU_Duration_Vs_RecruitmentForce_Stroke_Threshold_5_19_20 = data(:,39);
UNAFF_VAF.Report_MU_Duration_Vs_MeanFiringRate_Stroke_Threshold_5_19_2017 = data(:,40);
UNAFF_VAF.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_2017 = data(:,41);
UNAFF_VAF.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_1 = data(:,42);
UNAFF_VAF.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_19_20 = data(:,43);
UNAFF_VAF.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_15_20 = data(:,44);

%% Clear temporary variables
clearvars data raw stringVectors R;


%% Import the data
[~, ~, raw] = xlsread('C:\Users\Andrew\Lai_SMULab\Projects\BicepsSensorArray\Reports\ReportSummary_V3.xlsm','Summary Heatmap','A116:AS126');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
Difference = table;

%% Allocate imported array to column variable names
Difference.VarName1 = cellstr(stringVectors(:,1));
Difference.Report = data(:,1);
Difference.Report_MVC_Stroke_5_4_2017 = data(:,2);
Difference.Report_MVC_Stroke_5_24_2017 = data(:,3);
Difference.Report_MVC_Stroke_5_24_1 = data(:,4);
Difference.Report_MVC_Stroke_5_24_2 = data(:,5);
Difference.Report_MVC_Stroke_5_24_3 = data(:,6);
Difference.Report_MVC_Stroke_5_24_4 = data(:,7);
Difference.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_2017 = data(:,8);
Difference.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_1 = data(:,9);
Difference.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_2017 = data(:,10);
Difference.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_1 = data(:,11);
Difference.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2017 = data(:,12);
Difference.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_1 = data(:,13);
Difference.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2 = data(:,14);
Difference.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_2017 = data(:,15);
Difference.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_1 = data(:,16);
Difference.Report_SEMG_SensorArray_SNR_Stroke_5_22_2017 = data(:,17);
Difference.Report_SEMG_SensorArray_SNR_Stroke_5_22_1 = data(:,18);
Difference.Report_SEMG_SensorArray_SNR_Stroke_5_22_2 = data(:,19);
Difference.Report_SEMG_SensorArray_SNR_Stroke_5_22_3 = data(:,20);
Difference.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2017 = data(:,21);
Difference.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2017 = data(:,22);
Difference.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2017 = data(:,23);
Difference.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2017 = data(:,24);
Difference.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_1 = data(:,25);
Difference.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_1 = data(:,26);
Difference.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_1 = data(:,27);
Difference.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_1 = data(:,28);
Difference.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2 = data(:,29);
Difference.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2 = data(:,30);
Difference.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2 = data(:,31);
Difference.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2 = data(:,32);
Difference.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_2017 = data(:,33);
Difference.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_1 = data(:,34);
Difference.Report_MU_Amplitudes_Vs_RecruitmentForce_Stroke_Threshold_5_19_ = data(:,35);
Difference.Report_MU_Amplitudes_Vs_MeanFiringRate_Stroke_5_15_2017 = data(:,36);
Difference.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_2017 = data(:,37);
Difference.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_1 = data(:,38);
Difference.Report_MU_Duration_Vs_RecruitmentForce_Stroke_Threshold_5_19_20 = data(:,39);
Difference.Report_MU_Duration_Vs_MeanFiringRate_Stroke_Threshold_5_19_2017 = data(:,40);
Difference.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_2017 = data(:,41);
Difference.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_1 = data(:,42);
Difference.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_19_20 = data(:,43);
Difference.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_15_20 = data(:,44);

%% Clear temporary variables
clearvars data raw stringVectors R;


%% Import the data
[~, ~, raw] = xlsread('C:\Users\Andrew\Lai_SMULab\Projects\BicepsSensorArray\Reports\ReportSummary_V3.xlsm','Summary Heatmap','A128:AS138');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
Ratio = table;

%% Allocate imported array to column variable names
Ratio.VarName1 = cellstr(stringVectors(:,1));
Ratio.Report = data(:,1);
Ratio.Report_MVC_Stroke_5_4_2017 = data(:,2);
Ratio.Report_MVC_Stroke_5_24_2017 = data(:,3);
Ratio.Report_MVC_Stroke_5_24_1 = data(:,4);
Ratio.Report_MVC_Stroke_5_24_2 = data(:,5);
Ratio.Report_MVC_Stroke_5_24_3 = data(:,6);
Ratio.Report_MVC_Stroke_5_24_4 = data(:,7);
Ratio.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_2017 = data(:,8);
Ratio.Report_SEMG_SensorArray_vs_TargetForce_Stroke_5_18_1 = data(:,9);
Ratio.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_2017 = data(:,10);
Ratio.Report_SEMG_SensorArray_vs_TargetForce_Stroke_6_16_1 = data(:,11);
Ratio.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2017 = data(:,12);
Ratio.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_1 = data(:,13);
Ratio.Report_SEMG_SingleDifferential_vs_TargetForce_Stroke_5_19_2 = data(:,14);
Ratio.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_2017 = data(:,15);
Ratio.Report_SEMG_SensorArray_SNR_BothArrays_Stroke_5_18_1 = data(:,16);
Ratio.Report_SEMG_SensorArray_SNR_Stroke_5_22_2017 = data(:,17);
Ratio.Report_SEMG_SensorArray_SNR_Stroke_5_22_1 = data(:,18);
Ratio.Report_SEMG_SensorArray_SNR_Stroke_5_22_2 = data(:,19);
Ratio.Report_SEMG_SensorArray_SNR_Stroke_5_22_3 = data(:,20);
Ratio.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2017 = data(:,21);
Ratio.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2017 = data(:,22);
Ratio.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2017 = data(:,23);
Ratio.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2017 = data(:,24);
Ratio.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_1 = data(:,25);
Ratio.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_1 = data(:,26);
Ratio.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_1 = data(:,27);
Ratio.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_1 = data(:,28);
Ratio.Report_SEMG_SingleDifferential_SNR_Stroke_5_16_2 = data(:,29);
Ratio.Report_SEMG_SingleDifferential_SNR_Stroke_5_18_2 = data(:,30);
Ratio.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_16_2 = data(:,31);
Ratio.Report_SEMG_SingleDifferential_SNR_PtP_Stroke_5_18_2 = data(:,32);
Ratio.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_2017 = data(:,33);
Ratio.Report_MU_Amplitude_Statistics_Stroke_Threshold_5_19_1 = data(:,34);
Ratio.Report_MU_Amplitudes_Vs_RecruitmentForce_Stroke_Threshold_5_19_ = data(:,35);
Ratio.Report_MU_Amplitudes_Vs_MeanFiringRate_Stroke_5_15_2017 = data(:,36);
Ratio.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_2017 = data(:,37);
Ratio.Report_MU_Duration_vs_TargetForce_Stroke_Threshold_5_19_1 = data(:,38);
Ratio.Report_MU_Duration_Vs_RecruitmentForce_Stroke_Threshold_5_19_20 = data(:,39);
Ratio.Report_MU_Duration_Vs_MeanFiringRate_Stroke_Threshold_5_19_2017 = data(:,40);
Ratio.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_2017 = data(:,41);
Ratio.Report_MU_FiringRate_Statistics_Stroke_Threshold_5_19_1 = data(:,42);
Ratio.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_19_20 = data(:,43);
Ratio.Report_MU_FiringRate_vs_ThresholdForce_Stroke_Threshold_5_15_20 = data(:,44);

%% Clear temporary variables
clearvars data raw stringVectors R;


%%
varName = {'SID',...
           'Column1',...
           'MVC_Force',...
           'MVC_Medial_Array',...
           'MVC_Lateral_Array',...
           'MVC_BICM',...
           'MVC_BICL',...
           'MVC_BRD',...
           'MedialArray_CH1_SEMG_v_Target_Force',...
           'LateralArray_CH1_SEMG_v_Target_Force',...
           'MedialArray_SEMG_v_Target_Force',...
           'LateralArray_SEMG_v_Target_Force',...
           'BICM_v_Target_Force',...
           'BICL_v_Target_Force',...
           'BRD_v_Target_Force',...
           'BothArrays_RMS_SNR',...
           'BothArrays_RMS_SNR_v_Target_Force',...
           'MedialArray_RMS_SNR',...
           'MedialArray_RMS_SNR_v_Target_Force',...
           'LateralArray_RMS_SNR',...
           'LateralArray_RMS_SNR_v_Target_Force',...
           'BICM_RMS_SNR','BICM_RMS_SNR_v_Target_Force',...
           'BICM_PtP_SNR','BICM_PtP_SNR_v_Target_Force',...
           'BICL_RMS_SNR','BICL_RMS_SNR_v_Target_Force',...
           'BICL_PtP_SNR','BICL_PtP_SNR_v_Target_Force',...
           'BRD_RMS_SNR','BRD_RMS_SNR_v_Target_Force',...
           'BRD_PtP_SNR','BRD_PtP_SNR_v_Target_Force',...
           'BothArray_Mean_MU_Amplitude',...
           'BothArray_MU_Amplitude_v_Target_Force',...
           'BothArray_MU_Amplitude_v_Recruitment_Force',...
           'BothArray_MU_Amplitude_v_Firing_Rate',...
           'BothArray_Mean_MU_Duration',...
           'BothArray_MU_Duration_v_Target_Force',...
           'BothArray_MU_Duration_v_Recruitment_Force',...
           'BothArray_MU_Duration_v_Firing_Rate',...
           'BothArray_Mean_MU_Firing_Rate',...
           'BothArray_Firing_Rate_v_Target_Force',...
           'BothArray_Firing_Rate_v_Recruitment_Force',...
           'BothArray_Mean_MU_Threshold'};
AFF.Properties.VariableNames = varName;
UNAFF.Properties.VariableNames = varName;
AFF_VAF.Properties.VariableNames = varName;
UNAFF_VAF.Properties.VariableNames = varName;
Difference.Properties.VariableNames = varName;
Ratio.Properties.VariableNames = varName;
T_Test.Properties.VariableNames = varName;

AFF = AFF(2:end,:);
UNAFF = UNAFF(2:end,:);
AFF_VAF = AFF_VAF(2:end,:);
UNAFF_VAF = UNAFF_VAF(2:end,:);
T_Test = T_Test(2:end,:);
F_Test = F_Test(2:end,:);
Difference = Difference(2:end,:);
Ratio = Ratio(2:end,:);
